version: "3.7"
services:
  migration:
    depends_on:
      - db
    build: ./database
    environment:
      DATABASE_URL: "postgres://postgres:rn6yBZ1QG7x1asvBRzaX@db:5432/demo"
    links:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: rn6yBZ1QG7x1asvBRzaX
      POSTGRES_DB: demo
    volumes:
      - db-storage:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  db-storage: {}
